# Generated by Django 6.0.1 on 2026-01-26 23:43

from django.db import migrations

def add_birds(apps, schema_editor):
    BirdSpecies = apps.get_model('sightings', 'BirdSpecies')
    birds = [
        ('Northern Cardinal', 'Cardinalis cardinalis'),
        ('Grackle', 'Quiscalus quiscula'),
        ('Blue Jay', 'Cyanocitta cristata'),
        ('Northern Mockingbird', 'Mimus polyglottos'),
        ('Green Jay', 'Cyanocorax yncas'),
    ]

    for common, scientific in birds:
        BirdSpecies.objects.get_or_create(
            common_name=common,
            scientific_name=scientific
        )

class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_birds),
    ]