# Generated by Django 6.0.1 on 2026-01-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
