# Generated by Django 6.0.1 on 2026-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_sighting_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdspecies',
            name='category',
            field=models.CharField(choices=[('songbird', 'Songbirds'), ('waterfowl', 'Waterfowl'), ('raptor', 'Raptors'), ('shorebird', 'Shorebirds'), ('woodpecker', 'Woodpeckers'), ('owl', 'Owls'), ('seabird', 'Seabirds'), ('hummingbird', 'Hummingbirds'), ('gamebird', 'Gamebirds'), ('pigeon_dove', 'Pigeons & Doves'), ('parrot', 'Parrots'), ('penguin', 'Penguins'), ('flightless', 'Flightless Birds'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
