# Generated by Django 6.0.1 on 2026-02-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_comment_like'),
        ('sightings', '0006_populate_bird_categories'),
    ]

    operations = [
    ]
