# Generated by Django 6.0.1 on 2026-03-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0007_merge_0005_comment_like_0006_populate_bird_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sighting_images/'),
        ),
    ]
