# Generated by Django 6.0.1 on 2026-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0008_sighting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='weather_conditions',
            field=models.CharField(blank=True, help_text='e.g., Sunny, Cloudy, Rainy', max_length=100),
        ),
    ]
