# Generated by Django 6.0.1 on 2026-05-06 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0009_optional_latlong_weather'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_species', 'Incorrect Species'), ('fake', 'Fake Sighting/Spam'), ('inappropriate', 'Inappropriate Image/Content'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Provide additional details or the correct species name.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sightings.sighting')),
            ],
        ),
    ]
