# Generated by Django 6.0.1 on 2026-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0009_optional_latlong_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='behavior',
            field=models.CharField(blank=True, choices=[('perched', 'Perched'), ('feeding', 'Feeding'), ('flying', 'In Flight'), ('singing', 'Singing'), ('nesting', 'Nesting'), ('swimming', 'Swimming'), ('bathing', 'Bathing'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sighting',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Number of birds observed'),
        ),
    ]
