# Generated by Django 6.0.1 on 2026-05-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0011_merge_0010_behavior_count_0010_sightingreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdspecies',
            options={'verbose_name': 'Bird species', 'verbose_name_plural': 'Bird species'},
        ),
    ]
